grails-app/controllers/synthrone/exporters/EmailSenderController.groovy
package synthrone.exporters

import org.apache.commons.lang.RandomStringUtils

class EmailSenderController {

    def springSecurityService

    static final String TITLE_REMIND_PASSWORD = "Reset Password"
    static final String BODY_REMIND_PASSWORD = "Your new password: "
    static final String API_ACCESS = "API ACCESS"
    static final String API_IDENTITY = "ID: "
    static final String API_TOKEN = "TOKEN: "

    private String passwordMessage

    def index() {}

    def apiAccess(Client client) {
        respond client
    }

    def sendPassword() {
        String getEmailAddress = params.address
        def randomStringPassword = passwordGenerator()
        checkUserAndAssignPassword(getEmailAddress, randomStringPassword)
        try {
            sendMail {
                to getEmailAddress
                subject TITLE_REMIND_PASSWORD
                text BODY_REMIND_PASSWORD + passwordMessage
            }
            user.setPassword(springSecurityService.encodePassword(randomStringPassword))
            user.save flush: true
        } catch (IOException) {
            flash.message_2 = "Error. Please check if provided e-mail is valid"
            redirect action: "index"
            return
        }
        flash.message = "Message sent to your e-mail"
        redirect action: "index"
    }


    def sendApiKey(Client client) {
        String getEmailAddress = params.address
        def messageToSend = API_IDENTITY + client.getIdentity() + "\n" + API_TOKEN + client.getToken()
        try {
            sendMail {
                to getEmailAddress
                subject API_ACCESS
                text messageToSend
            }
            client.setAccountActive(true)
            client.save flush: true
        } catch (IOException) {
            flash.message_2 = "Error. Please check if provided e-mail is valid"
            redirect(action: "apiAccess", id: client.id)
            return
        }
        redirect(controller: "client", action: "index")
    }


    def passwordGenerator() {
        return RandomStringUtils.random(9, true, true)
    }


    def checkUserAndAssignPassword(String username, String newPassword) {
        def user = User.findByUsername(username)
        if (user != null) {
            passwordMessage = newPassword
        } else {
            passwordMessage = "You are not registered. Please contact the administrator."
        }
    }

}

grails-app/views/emailSender/apiAccess.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Email Sender</title>
</head>

<body>
<div id="content" role="main">

    <div class="container container-table" style="padding-top: 80px">
        <div class="row vertical-center-row">
            <div class="text-center col-md-6 col-md-offset-3"
                 style="border: 1px solid #ccc;border-radius: 20px;padding: 30px;">
                <section class="row colset-2-its">
                    <h2 style="color: firebrick">Send API Keys</h2>
                    <g:form controller="emailSender" action="sendApiKey" style="margin: 25px 30px 25px 30px">
                        <div class="fieldcontain" style="margin-bottom: 25px; margin-top: 25px">
                            <h4 class="form-signin-heading text-left">Client email:</h4>
                            <g:field type="email" class="form-control" name="address" required=""/>
                        </div>
                        <fieldset>
                            <g:submitButton class="btn btn-success btn-lg" name="send" value="SEND"/>
                        </fieldset>
                        <input type="hidden" name="identity" value="${client.identity}"/>
                        <input type="hidden" name="token" value="${client.token}"/>
                        <input type="hidden" name="id" value="${client.id}"/>
                    </g:form>
                </section>
                <g:if test="${flash.message}">
                    <div class="alert alert-success" role="alert" style="margin-top: 25px">
                        ${flash.message}
                    </div>
                </g:if>
                <g:if test="${flash.message_2}">
                    <div class="alert alert-danger" role="alert" style="margin-top: 25px">
                        ${flash.message_2}
                    </div>
                </g:if>
            </div>
        </div>
    </div>

</div>
</body>
</html>

grails-app/views/emailSender/index.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Email Sender</title>
</head>

<body>
<div id="content" role="main">
    <div class="container container-table" style="padding-top: 80px">
        <div class="row vertical-center-row">
            <div class="text-center col-md-6 col-md-offset-3"
                 style="border: 1px solid #ccc;border-radius: 20px;padding: 30px;">
                <section class="row colset-2-its">
                    <h2 style="color: firebrick">Reset Password</h2>
                    <g:form controller="emailSender" action="sendPassword" style="margin: 25px 30px 25px 30px">
                        <div class="fieldcontain" style="margin-bottom: 25px; margin-top: 25px">
                            <h4 class="form-signin-heading text-left">Your email:</h4>
                            <g:field type="email" class="form-control" name="address" required=""/>
                        </div>
                        <fieldset>
                            <g:submitButton class="btn btn-primary btn-lg" name="send" value="Reset"/>
                        </fieldset>
                    </g:form>
                </section>
                <g:if test="${flash.message}">
                    <div class="alert alert-success" role="alert" style="margin-top: 25px">
                        ${flash.message}
                    </div>
                </g:if>
                <g:if test="${flash.message_2}">
                    <div class="alert alert-danger" role="alert" style="margin-top: 25px">
                        ${flash.message_2}
                    </div>
                </g:if>
            </div>
        </div>
    </div>

</div>
</body>
</html>